-- +migrate up
create table votes (
  id int generated by default as identity primary key,
  user_id bigint not null,
  weekend bool not null,
  type text not null,
  created_at timestamptz default now() not null
);

create index ix_votes_user on votes(user_id);

-- +migrate down
drop table votes;
