-- +migrate up
create table command_uses (
  id int generated by default as identity primary key,
  message_id bigint not null,
  user_id bigint not null,
  command text not null,
  args text,
  "timestamp" timestamptz default now() not null
);

create index ix_command_uses_command on command_uses(command);
create index ix_command_uses_timestamp on command_uses("timestamp");
create index ix_command_uses_user on command_uses(user_id);

-- +migrate down
drop table command_uses;
